server:
  port: 12580
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: springboot-demo-temp
  profiles:
    # ${}方式会被maven处理，但是这里不起作用
    # 原因是如果pom继承了spring-boot-starter-parent，springboot会替换maven-resources-plugins默认的${}方式为‘@@’方式，例如@name@
    # active: ${profiles.active}
    active: @profiles.active@

# Knife4j配置自定义属性
knife4j-custom:
  title: Knife4j接口文档 - ${spring.application.name}
  version: 1.0.0
  description: Knife4j接口文档 - description
  base-package: com.example.temp.controller
